packages:
  - "1-Identity & Access"
  - "2-Core Data Model & API"
  - "4-File Asset Hub"
  - "5-Unified Inbox"
  - "6-Client 360"
  - "7-Service Factories"
  - "8-Approvals Center"
  - "9-QA Gates & Checks"
  - "10-Reporting & KPIs"
  - "12-Admin Integrations Hub"
  - "13-Bundlr Budgets"
  - "_Shared"
  - "shell"
  - "lib/supabase"
