import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Report, ReportStatus } from '../types';
import { ArrowLeft, CheckCircle, Send, Printer, Share2 } from 'lucide-react';

interface ReportDetailProps {
  report: Report;
  onBack: () => void;
  onApprove: (id: string) => void;
  onSend: (id: string) => void;
}

const ReportDetail: React.FC<ReportDetailProps> = ({ report, onBack, onApprove, onSend }) => {
  return (
    <div className="max-w-5xl mx-auto h-[calc(100vh-2rem)] flex flex-col">
      {/* Header Toolbar */}
      <div className="flex items-center justify-between mb-6 pb-4 border-b border-slate-200 flex-shrink-0">
        <div className="flex items-center gap-4">
          <button 
            onClick={onBack}
            className="p-2 hover:bg-slate-200 rounded-full text-slate-500 transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <h2 className="text-xl font-bold text-slate-900">{report.title}</h2>
            <div className="flex items-center gap-2 text-sm text-slate-500">
               <span>Status: {report.status}</span>
               {report.generatedAt && <span>• Generated: {new Date(report.generatedAt).toLocaleString()}</span>}
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <button className="p-2 text-slate-400 hover:text-slate-600">
             <Printer className="w-5 h-5" />
          </button>
           <button className="p-2 text-slate-400 hover:text-slate-600 mr-2">
             <Share2 className="w-5 h-5" />
          </button>

          {report.status === ReportStatus.GENERATED && (
            <button 
              onClick={() => onApprove(report.id)}
              className="flex items-center gap-2 px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 font-medium transition-colors"
            >
              <CheckCircle className="w-4 h-4" />
              Approve Report
            </button>
          )}

          {report.status === ReportStatus.APPROVED && (
            <button 
              onClick={() => onSend(report.id)}
              className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium transition-colors"
            >
              <Send className="w-4 h-4" />
              Send to Stakeholders
            </button>
          )}
          
          {report.status === ReportStatus.SENT && (
             <div className="px-4 py-2 bg-slate-100 text-slate-500 rounded-lg font-medium flex items-center gap-2">
               <CheckCircle className="w-4 h-4" />
               Sent
             </div>
          )}
        </div>
      </div>

      {/* Document View */}
      <div className="flex-1 overflow-auto bg-white rounded-xl shadow-sm border border-slate-200 p-12 md:p-16 prose-content">
        <article className="prose prose-slate prose-lg max-w-none font-serif text-slate-800 leading-relaxed">
          {/* We render markdown content here. Ideally, specific components for H1, H2 could be styled via components prop */}
          {report.content ? (
             <ReactMarkdown 
               components={{
                 h1: ({node, ...props}) => <h1 className="text-3xl font-bold text-slate-900 mb-6" {...props} />,
                 h2: ({node, ...props}) => <h2 className="text-xl font-bold text-indigo-900 mt-8 mb-4 border-b border-indigo-100 pb-2" {...props} />,
                 p: ({node, ...props}) => <p className="mb-4 text-slate-700" {...props} />,
                 ul: ({node, ...props}) => <ul className="list-disc list-outside ml-6 mb-6 space-y-2" {...props} />,
                 li: ({node, ...props}) => <li className="text-slate-700" {...props} />,
               }}
             >
               {report.content}
             </ReactMarkdown>
          ) : (
            <div className="flex flex-col items-center justify-center h-full text-slate-400">
               <p>Report content is empty or loading...</p>
            </div>
          )}
        </article>
      </div>
      
      {/* Footer / Meta info */}
      <div className="mt-4 text-center text-xs text-slate-400 flex-shrink-0 pb-4">
        CONFIDENTIAL - INTERNAL USE ONLY • Generated by Narrative BI
      </div>
    </div>
  );
};

export default ReportDetail;